project_id = "mzqoneroabpdfeucyera"

[functions.verify-password]
verify_jwt = false

[functions.get-recordings]
verify_jwt = false

[functions.setup-initial-admin]
verify_jwt = false

[functions.manage-roles]
verify_jwt = false

[functions.download-recording]
verify_jwt = false
